# Fast Text AI Demo

name: fastTextAIDemo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls -lR

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          which python
          which gcc
          cd fastText20220622
          make
          cd ../trainingdata
          ../fastText20220622/fasttext supervised -input cooking.train -output model_cooking > training.log
          #ls -l model*
          echo "PREDICT DEMO"
          ../fastText20220622/fasttext predict model_cooking.bin cooking.valid
          echo "END DEMO"